version: '2'
services:
  app:
    build: .
    ports:
     - "80:80"
    volumes:
     - ./src:/var/www/html
     - ./config.php:/var/www/html/config.php
    depends_on:
     - db
  db:
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: hackspace
      MYSQL_DATABASE: hackspace
      MYSQL_USER: hackspace
      MYSQL_PASSWORD: hackspace